# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_product_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='/media/qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='products_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(max_length=255, unique=True)),
                ('type1', models.CharField(max_length=255)),
                ('product_qty', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='model_product_id',
            name='model_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addTxn.products_data'),
        ),
    ]
